CREATE VIEW DADOS_PESSOA_TEM_DEPENDENTES AS 
(SELECT NUMERO_AGENCIA, NUMERO_CONTA FROM MOVIMENTA 
WHERE CPF IN (SELECT CPF_PARENTE FROM DEPENDENTE 
GROUP BY CPF_PARENTE HAVING COUNT(*) >= 3));

SELECT NUMERO_AGENCIA, NUMERO_CONTA 
FROM (SELECT * 
FROM CONTA 
WHERE NUMERO_AGENCIA IN (SELECT NUMERO_AGENCIA FROM DADOS_PESSOA_TEM_DEPENDENTES) 
AND NUMERO_CONTA IN (SELECT NUMERO_CONTA FROM DADOS_PESSOA_TEM_DEPENDENTES)) 
WHERE SALDO_ATUAL IN (SELECT MAX (SALDO_ATUAL) FROM (SELECT * FROM CONTA 
WHERE NUMERO_AGENCIA IN (SELECT NUMERO_AGENCIA FROM DADOS_PESSOA_TEM_DEPENDENTES) 
AND NUMERO_CONTA IN (SELECT NUMERO_CONTA FROM DADOS_PESSOA_TEM_DEPENDENTES)));